Update README.md
SavvaKulikov/market_bot pull request #1
Opened 2024-10-20 20:43 UTC by SavvaKulikov

Техническое задание

2024-10-20 20:54 UTC, dKosarevsky requested changes
нужно добавить:

- тему проекта
- ФИО
- номер группы
- библиотеки, планируемые для использования
- версии python, которые будет поддерживать приложение
- развёрнутое описание архитектуры

2024-10-21 14:09 UTC, SavvaKulikov commented
> нужно добавить:
> 
>     * тему проекта
> 
>     * ФИО
> 
>     * номер группы
> 
>     * библиотеки, планируемые для использования
> 
>     * версии python, которые будет поддерживать приложение
> 
>     * развёрнутое описание архитектуры

2024-10-29 20:57 UTC, dKosarevsky commented
Где необходимые правки?

2024-11-03 23:27 UTC, dKosarevsky commented
будут ли правки?

2024-12-17 06:20 UTC, merged